"""Setup Weave Table

Revision ID: 2e79ce2477b3
Revises: 
Create Date: 2026-02-09 20:56:25.088953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e79ce2477b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('weaves',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('family_weave',
    sa.Column('weave_uuid', sa.UUID(), nullable=False),
    sa.Column('family_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['family_uuid'], ['families.uuid'], ),
    sa.ForeignKeyConstraint(['weave_uuid'], ['weaves.uuid'], ),
    sa.PrimaryKeyConstraint('weave_uuid', 'family_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_weave')
    op.drop_table('weaves')
    op.drop_table('families')
    # ### end Alembic commands ###
