"""Add name column to weave table

Revision ID: cdda2fcb04c3
Revises: 2e79ce2477b3
Create Date: 2026-02-09 21:01:53.143576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdda2fcb04c3'
down_revision: Union[str, Sequence[str], None] = '2e79ce2477b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weaves', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weaves', 'name')
    # ### end Alembic commands ###
