"""Update Weave Table with Base Values

Revision ID: de4d8b1f391f
Revises: cdda2fcb04c3
Create Date: 2026-02-09 21:05:50.282878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4d8b1f391f'
down_revision: Union[str, Sequence[str], None] = 'cdda2fcb04c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weaves', sa.Column('description', sa.String(), nullable=True))
    op.add_column('weaves', sa.Column('min_ar', sa.Float(), nullable=True))
    op.add_column('weaves', sa.Column('max_ar', sa.Float(), nullable=True))
    op.add_column('weaves', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('weaves', sa.Column('tutorial_link', sa.String(), nullable=True))
    op.add_column('weaves', sa.Column('multi_ringsize', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weaves', 'multi_ringsize')
    op.drop_column('weaves', 'tutorial_link')
    op.drop_column('weaves', 'picture')
    op.drop_column('weaves', 'max_ar')
    op.drop_column('weaves', 'min_ar')
    op.drop_column('weaves', 'description')
    # ### end Alembic commands ###
